# Generated by Django 6.0.3 on 2026-04-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devoluciones', '0002_returnincident_customer_fiscal_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('comercial', 'Comercial'), ('administracion', 'Administración'), ('almacen', 'Almacén')], max_length=30, verbose_name='rol')),
                ('all_representatives', models.BooleanField(default=False, verbose_name='todos los representantes')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de acceso',
                'verbose_name_plural': 'perfiles de acceso',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserRepresentativeScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_scopes', to='core.useraccessprofile', verbose_name='perfil')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='devoluciones.representative', verbose_name='representante')),
            ],
            options={
                'verbose_name': 'alcance de representante',
                'verbose_name_plural': 'alcances de representantes',
                'ordering': ['profile__user__username', 'representative__code'],
                'unique_together': {('profile', 'representative')},
            },
        ),
    ]
