# Generated by Django 6.0.3 on 2026-04-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderincidentline',
            name='quantity_incident',
        ),
    ]
