# Generated by Django 6.0.3 on 2026-04-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_orderincidentline_quantity_incident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderincident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre'),
        ),
        migrations.AddField(
            model_name='orderincident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_incidents_closed', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por'),
        ),
        migrations.AddField(
            model_name='orderincident',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='como se ha solucionado'),
        ),
        migrations.AlterField(
            model_name='orderincident',
            name='status',
            field=models.CharField(choices=[('pending', 'Abierta'), ('in_progress', 'En trámite'), ('closed', 'Cerrada')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
