# Generated by Django 6.0.3 on 2026-03-24 15:12

import devoluciones.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'representante',
                'verbose_name_plural': 'representantes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReturnIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='numero de incidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('delivery_note_number', models.CharField(max_length=50, verbose_name='numero de albaran')),
                ('delivery_note_date', models.DateField(blank=True, null=True, verbose_name='fecha de albaran')),
                ('customer_name', models.CharField(max_length=255, verbose_name='cliente')),
                ('representative_code', models.CharField(max_length=20, verbose_name='codigo de representante')),
                ('representative_name', models.CharField(max_length=255, verbose_name='nombre de representante')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('destination', models.CharField(max_length=255, verbose_name='destino')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('closed', 'Cerrada')], default='pending', max_length=20, verbose_name='estado')),
                ('total_selected_lines', models.PositiveIntegerField(default=0, verbose_name='total de lineas seleccionadas')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_incidents_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'incidencia de devolucion',
                'verbose_name_plural': 'incidencias de devolucion',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=devoluciones.models.incident_attachment_upload_to, verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido el')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='devoluciones.returnincident', verbose_name='incidencia')),
            ],
            options={
                'verbose_name': 'adjunto de incidencia',
                'verbose_name_plural': 'adjuntos de incidencia',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnIncidentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_number', models.CharField(max_length=50, verbose_name='numero de albaran')),
                ('delivery_note_line', models.PositiveIntegerField(verbose_name='linea de albaran')),
                ('article_code', models.CharField(max_length=50, verbose_name='codigo de articulo')),
                ('article_description', models.CharField(max_length=255, verbose_name='descripcion de articulo')),
                ('quantity_delivery_note', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad albaran')),
                ('quantity_incident', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad incidencia')),
                ('sale_lot', models.CharField(blank=True, max_length=50, verbose_name='lote de venta')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='devoluciones.returnincident', verbose_name='incidencia')),
            ],
            options={
                'verbose_name': 'linea de incidencia',
                'verbose_name_plural': 'lineas de incidencia',
                'ordering': ['incident_id', 'delivery_note_line', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_links', to='devoluciones.representative', verbose_name='representante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative_link', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'usuario-representante',
                'verbose_name_plural': 'usuarios-representante',
                'ordering': ['user__username'],
            },
        ),
    ]
