# Generated by Django 6.0.3 on 2026-03-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnincident',
            name='customer_fiscal_address',
            field=models.CharField(blank=True, max_length=30, verbose_name='direccion fiscal'),
        ),
    ]
