# Generated by Django 6.0.3 on 2026-04-22 11:23

import django.db.models.deletion
import transporte.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='numero de incidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('has_delivery_note', models.BooleanField(default=False, verbose_name='tiene albaran')),
                ('delivery_note_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='numero de albaran')),
                ('delivery_note_date', models.DateField(blank=True, null=True, verbose_name='fecha de albaran')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='cliente')),
                ('representative_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='codigo de representante')),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre de representante')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('carrier', models.CharField(choices=[('MRW', 'MRW'), ('GLS', 'GLS'), ('SEUR', 'SEUR'), ('Dachser', 'Dachser'), ('Integra2', 'Integra2'), ('MBE', 'MBE'), ('DHL', 'DHL'), ('Correos', 'Correos'), ('CTT', 'CTT'), ('DSV', 'DSV')], max_length=30, verbose_name='transportista')),
                ('incident_type', models.CharField(choices=[('lost_package', 'Bulto perdido'), ('damaged_goods', 'Daños en mercancía'), ('delay', 'Retraso'), ('failed_delivery', 'Entrega fallida'), ('other', 'Otro')], max_length=30, verbose_name='tipo de incidencia')),
                ('status', models.CharField(choices=[('pending', 'Abierta'), ('in_progress', 'En trámite'), ('closed', 'Cerrada')], default='pending', max_length=20, verbose_name='estado')),
                ('shipment_direction', models.CharField(choices=[('shipment', 'Envío'), ('pickup', 'Recogida')], max_length=20, verbose_name='envio o recogida')),
                ('tracking_number', models.CharField(max_length=100, verbose_name='numero de seguimiento')),
                ('internal_reference', models.CharField(max_length=100, verbose_name='referencia interna')),
                ('country', models.CharField(default='España', max_length=100, verbose_name='pais')),
                ('province', models.CharField(max_length=100, verbose_name='provincia')),
                ('municipality', models.CharField(max_length=100, verbose_name='municipio')),
                ('sender', models.CharField(max_length=255, verbose_name='remitente')),
                ('recipient', models.CharField(max_length=255, verbose_name='destinatario')),
                ('shipping_date', models.DateField(verbose_name='fecha de envio')),
                ('incident_date', models.DateField(verbose_name='fecha de incidencia')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='como se ha solucionado')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_incidents_closed', to=settings.AUTH_USER_MODEL, verbose_name='cerrado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_incidents_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'incidencia de transporte',
                'verbose_name_plural': 'incidencias de transporte',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransportIncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=transporte.models.transport_incident_attachment_upload_to, verbose_name='archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subido el')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transporte.transportincident', verbose_name='incidencia')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_incident_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'adjunto de incidencia de transporte',
                'verbose_name_plural': 'adjuntos de incidencias de transporte',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
